spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tealeaves?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: fooddelivery8886@gmail.com
    password: qdcnvspmxdhiocwp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  privateKey: 6XzQSdIb+GvHPYOZ6tynDcIutj32FkZSTHK4LumtbRA=

FileUpload:
  rootPath: C:\Users\HAINAM\uploads

mqtt:
  broker: ssl://7e44c054e3384872bc6b019a4185eb18.s1.eu.hivemq.cloud:8883
  username: iec-local
  password: Aa12345678
  clean-session: true
  client-id: springtealeaves
  qr-topic: esp32/data