spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tealeaves?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: hainam
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: fooddelivery8886@gmail.com
    password: qdcnvspmxdhiocwp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  privateKey: 6XzQSdIb+GvHPYOZ6tynDcIutj32FkZSTHK4LumtbRA=

FileUpload:
  rootPath: C:\Users\HAINAM\uploads
